spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sku
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bumjun123@
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: qjawns314@gmail.com
    password: jbnz buhx nprk mhlp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    check-template-location: true
    cache: false
    mode: HTML5